### ISSUE TITLE
Output to "Tasks" view instead of "Status Bar Tasks"

### ISSUE THREAD

**Issue by blackwind** [GuardRex/vscode-status-bar-tasks#11]
In the spirit of #8 and properly integrating with VSCode rather than stubbornly cutting its own path, I'd like to suggest that SBT output to the existing "Tasks" view of the output console instead of its own "Status Bar Tasks" view.

**Comment by guardrex** [comment]
> rather than stubbornly cutting its own path

ha!

> output to the existing "Tasks" view

You can't. The API doesn't permit it. This is one that is truly out of my hands. [But I **wholeheartedly** agree with you!!!] See: https://github.com/Microsoft/vscode/issues/6192

**Comment by blackwind** [comment]
Ah, of course. Gotta love API limitations!

**Comment by guardrex** [comment]
Since I opened that issue, I might get flagged if they start to permit attaching to the Tasks output. I'm going to close this issue b/c there's nothing I can do about this, but I will try to keep an eye on them regarding this issue. Eventually, I'll ping them on it and ask if it's still under consideration.

**Comment by blackwind** [comment]
A thought: See Microsoft/vscode#6550 and Microsoft/vscode#10676, which are scheduled for the September milestone. Perhaps SBT could simply launch tasks via this new method, which would take care of both this and #8.

**Comment by guardrex** [comment]
Hi ... sorry for the insanely long delay. I'm getting slammed right now with professional projects, and there is even the possibility that I might have to pull this extension down I'm getting so busy these days.

I wish they would just offer a button-based system for launching tasks. I get keyboard launch is more important, but people do like to click on things! :smile:

cc/ @dbaeumer  ... You're seeing this, right? https://marketplace.visualstudio.com/items?itemName=GuardRex.status-bar-tasks ... It's somewhat popular, and you could do a **much better** job with it from the team than this hack I've thrown up.

Anyway ... I'll get back to this as soon as I can, but I'm probably going to be swamped with work for another two weeks. Thanks for alerting me to those issues, and I'll definitely take a close look at them when I get back to this. The line `public static ID = 'workbench.action.tasks.runTask/' + taskName;` is very intreaguing, because I might be able to hook into their existing task execution engine.

**Comment by guardrex** [comment]
They said they're going to take a fresh look at the entire tasks system in January. We're still on hold here to see which way they go. :watch:

**Comment by blackwind** [comment]
We now have the [`workbench.action.tasks.runTask` command](https://code.visualstudio.com/updates/v1_10#_task-support). Is that sufficient to get this one and #18 done?

**Comment by guardrex** [comment]
Possibly ... only one tiny (**GIANT**) snag ... I was just hired by Microsoft. Yeah. I'm not kidding. However, I will try to test with `runTask` on the 2nd or 3rd weekend of this month. No promises tho. Microsoft comes first.

**Comment by blackwind** [comment]
Hah, congratulations! By all means, keep your eyes on the prize. Another few weeks won't hurt.

**Comment by guardrex** [comment]
Thanks ... yeah ... it's awesome! ... It should be easy to test out that command. It shouldn't take more than an hour or two. I know the next weekend or two will be a little rough getting settled into the new schedule, but I anticipate having my weekends back in a couple of weeks. I'll leave this in my Inbox to remind me.

**Comment by guardrex** [comment]
I finally have some time to look at these issues and do a quick update on the extension. I've decided to stick with Node's `child_process` module. It's been sooooo reliable for me here. I'm not sure what behavioral differences there would be with `workbench.action.tasks.runTask` (maybe none). I hate to adopt the stupid "if it ain't broke" philosophy; but although I have some time to work on the extension, I really only have a couple of hours. Thanks tho for the suggestion/recommendation.
