### ISSUE TITLE
Multiple variable substitutions don't work

### ISSUE THREAD

**Issue by BillDenton** [GuardRex/vscode-status-bar-tasks#14]
When substituting a variable more once the second one doesn't get substituted. For example:
      {
         "taskName": "Cmd Prompt Build",
         "args": ["cd ${workspaceRoot}\\build && start cmd.exe /k title ${workspaceRoot} Build"]
      },

Gives a command prompt with title "${workspaceRoot} Build" rather than, for example, c:\code\build Build.

**Comment by guardrex** [comment]
Yes, this is because I didn't setup a global replacement by mistake ... I'm too accustomed to C# `.Replace()`, which will replace all occurrences.

https://github.com/GuardRex/vscode-status-bar-tasks/blob/master/status-bar-tasks/src/extension.ts#L81

Looks like the split/replace approach gets a lot of dev love ...
```javascript
str.split(search).join(replacement)
```
... so I'll give that a shot.

I'll get a fix in for this asap and ping you back here when it goes live.

**Comment by guardrex** [comment]
Fix on this is forthcoming. I'm going to knock out a few issues in one shot.

**Comment by guardrex** [comment]
This is fixed with latest version in the gallery (v.0.1.2). Thanks for pointing it out.

**Comment by BillDenton** [comment]
Verified fixed. Thanks.
