### ISSUE TITLE
Doesn't work if tasks should be run not from workspaceRoot

### ISSUE THREAD

**Issue by skazarynau** [GuardRex/vscode-status-bar-tasks#16]
This is my tasks.json

{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "options": {
        "cwd": "${workspaceRoot}/somefolder"
    },
    "version": "0.1.0",
    "command": "cmd",
    "isShellCommand": true,
    "args": ["/C"],
    "showOutput": "always",
    "suppressTaskName": true,
    "tasks": [
        {
            "taskName": "cleanall",
            "suppressTaskName": true,
            "args": ["python waf cleanall"]
        },
        {
            "taskName": "configure",
            "suppressTaskName": true,
            "args": ["python waf configure"]
        }
    ]
}

There is cwd defined. Tasks should be run from ${workspaceRoot}/somefolder. It seems that they are always run from ${workspaceRoot}. So I get:
`python: can't open file 'waf': [Errno 2] No such file or directory`

**Comment by guardrex** [comment]
Correct, `cwd` isn't supported by the extension.

Is there any chance that using your path on the arguments will work as a workaround?
```json
{
  "taskName": "cleanall",
  "suppressTaskName": true,
  "args": ["python ${workspaceRoot}/somefolder/waf cleanall"]
},
```

**Comment by skazarynau** [comment]
Hi,
I tried your idea. Unfortunately I get other error:
`Waf: Run from a directory containing a file named 'wscript'`

So maybe the only workaround is to create batch files for every task

**Comment by guardrex** [comment]
I'm not sure on what to do. I've taken the extension as far as I can right now in terms of its features. I had no idea it was going to become as popular as it has. Of course, I don't make a dime off of it. I really only ever made it in the first place for my own use and just threw it up there for a few friends who wanted to use it. I had no idea it would be as popular as it is. My time is very limited as I work on projects and contribute to ASP.NET documentation efforts, so I don't think I'll have time to implement anything for `cwd`. If you or someone wants to float a PR, I'll consider taking a contribution.

**Comment by guardrex** [comment]
I'm going to close this one because it's a little beyond the scope of what the extension can do OOB without a lot more work (well ... more than 10 minutes! ... I only have this evening for a quick update). What I've been doing to overcome any kind of directory issues is just give it the full path to whatever I need it to process. For example in the case of a .NET Core sample for Razor Pages testing where the folder structure looks like this ...

```
project
    .vscode
        tasks.json
    src
        RazorPagesTestingSample
    tests
        RazorPagesTestingSample.Tests
```
I can open the project in VSC at the root there (the `project` folder). The tasks to restore, build, and test just go like this with paths in the arguments:

* `"args" : ["dotnet", "restore", "src/RazorPagesTestingSample"],`
* `"args" : ["dotnet", "restore", "tests/RazorPagesTestingSample.Tests"],`
* `"args" : ["dotnet", "build", "tests/RazorPagesTestingSample.Tests", "--configuration", "Debug"],`
* `"args" : ["dotnet", "test", "tests/RazorPagesTestingSample.Tests", "--configuration", "Debug"],`

... so although it can't base anything off the cwd, it can find the paths under the cwd relatively speaking.
