### ISSUE TITLE
"tasks.args" is ignored 

### ISSUE THREAD

**Issue by kobalicek** [GuardRex/vscode-status-bar-tasks#19]
I don't have much to add, when I installed this extension it was working great, but after some updates it doesn't work anymore.

My tasks (a bit stripped):

```json
{
  "version": "0.1.0",
  "command": "bash",
  "args": ["-c"],
  "isShellCommand": true,
  "showOutput": "always",
  "suppressTaskName": true,
  "tasks": [
    {
      "taskName": "Build",
      "args": ["${workspaceRoot}/manage.sh build"],
      "isBuildCommand": true
    }
  ]
}
```

When I click "Build" it doesn't pass arguments to the script, so `manage.sh` is called with no arguments and thus does nothing. BTW thanks for this extension, I really like it, if it was working :)

**Comment by guardrex** [comment]
Try separating those into separate arguments.

Instead of using ...
```
"args": ["${workspaceRoot}/manage.sh build"],
```
... try it like this ...
```
"args": ["${workspaceRoot}/manage.sh", "build"],
```

**Comment by kobalicek** [comment]
Unfortunately that doesn't work for me, it also doesn't work in vs code anymore if I separate it that way. I guess would have to live without it :) But thanks for your reply!

**Comment by guardrex** [comment]
I'll do a test here with your task setup and see if I can repro the issue. I'll be home in a few hours to try it and report back.

**Comment by guardrex** [comment]
I find it confusing that its not working. I can't repro the problem here.

The code that assembles the command and arguments to run is very vanilla ... it just combines the arguments and sticks them on the command and then uses Node's `child_process` to run it.

Can you confirm your VS Code version? It should be v1.9.1. It's shown under `Help > About` in the menubar.

Can you run a test task and post back the output? Add this to your `tasks.json` file, save the file, and then run it from the Status Bar. It should provide a string that shows that it is combining everything correctly. In theory, you will see a string come back `<workspace root>/manage.sh build` ... if so, it is assembling the string correctly.
```
{
    "taskName": "echo test",
    "command": "echo",
    "args" : ["${workspaceRoot}/manage.sh", "build"],
    "showOutput": "always",
    "isBuildCommand": false
}
```
As a side-note, you can try using the new "command" property, but I doubt it will make a difference here:
```
{
  "version": "0.1.0",
  "command": "bash",
  "args": ["-c"],
  "isShellCommand": true,
  "showOutput": "always",
  "suppressTaskName": true,
  "tasks": [
    {
      "taskName": "Build",
      "command": "${workspaceRoot}/manage.sh",
      "args": ["build"],
      "isBuildCommand": true
    }
  ]
}
```
Ordinarily, your command would include the top-level command and would be ...
```
bash -c <workspace root>/manage.sh build
```
, but doing it that way :point_up: with a "command" on the task, it should just use the command and arguments  (no "bash -c") and try to run ...
```
<workspace root>/manage.sh build
```
Try it that way and see if removing the "bash -c" makes a difference.

**Comment by alan-null** [comment]
Hello @GuardRex 

I am facing the same problem
**VSC version:**
![image](https://cloud.githubusercontent.com/assets/6848691/23832187/409adf7a-0730-11e7-9c7a-db658086c59e.png)

**System**: Windows 10 x64


My `tasks.json` file
```json
{
    "version": "2.0.0",
    "command": "powershell",
    "args": [
        "-ExecutionPolicy",
        "Unrestricted",
        "-NoProfile",
        "-File",
        "${cwd}/build.ps1"
    ],
    "taskSelector": "-task ",
    "showOutput": "always",
    "tasks": [
        {
            "taskName": "build",
            "showOutput": "always",
            "isBuildCommand": true
        },
        {
            "taskName": "latest",
            "showOutput": "always",
            "isBuildCommand": true
        },
        {
            "taskName": "both",
            "showOutput": "always",
            "isBuildCommand": true
        }
    ]
}
```

`build.ps1`
```powershell
$taskName = $args[0].ToString().Replace("-task ","")
Write-Host "Task Name: $($taskName)"
```

Running it with `Ctrl+Shift+B`
```
Task Name: build
Press any key to close the terminal
```

Running it via status bar button
```
The argument '${cwd}/build.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.
Windows PowerShell 
Copyright (C) 2016 Microsoft Corporation. All rights reserved.
```

Please find attached zip folder with all files inside
[test.zip](https://github.com/GuardRex/vscode-status-bar-tasks/files/836537/test.zip)

**Comment by guardrex** [comment]
@alan-null It's more limited than what VSC fully offers now. `${cwd}` is not a supported variable. You'll have to explicitly add that path or see if you can use `${workspaceRoot}` along with hardcoded directories after it to assemble the path to your CWD. The variables that are supported are listed in the README.

Also note that `taskSelector` and `taskName` combo won't work, you'd have to configure that part as I show below to make it work.

You won't be able to make it fire both commands in one task unless you put them into a script and then have the extension execute the script. In order to make a script work, you'd have to move the top-level command `powershell` into a `command` on each task, then add all of those top-level PowerShell `args` (i.e., `-ExecutionPolicy`, `-NoProfile`, and `-File`) down to the `args` lists on each of these two commands `build` and `latest`. Then, make your third `command` and `args` on the 3rd task just fire off the PS script. 

When the extension sees that top-level PS `command` and `args` the way you show above it applies them to every task. To have a task doing something completely different, like run a script, means that you should only use the `command` and `args` on each task and not use the top-level `command` and `args` at all.

```json
"tasks": [
    {
        "taskName": "build",
        "suppressTaskName": true,
        "args" : ["-task", "build"],
        "showOutput": "always",
        "isBuildCommand": true
    },
    {
       "taskName": "latest",
        "suppressTaskName": true,
        "command": "dotnet",
        "args" : ["-task", "latest"],
        "showOutput": "always",
        "isBuildCommand": true
    }
```
Extending its capabilities further isn't going to be possible. I'm working 50+ hours a week these days on professional projects.

**Comment by alan-null** [comment]
@GuardRex thanks so much for the reply. I will give a try and check workarounds. 
I saw that the author was inactive after your latest reply so I wanted to provide more information in case you wanted to fix it. 

Thanks for work you've done so far.

**Comment by guardrex** [comment]
@alan-null I wouldn't mind working on it, but I work 50+ hours per week on professional projects. This extension was just something I did to help myself with basic .NET Core web dev projects and just threw it up on the Marketplace in case anyone wanted to use it. I had no idea it was going to take off like this with thousands of devs using it. IMO Microsoft should give VSC a toolbar with the tasks in it and "put me out of business" here. lol

**Comment by alan-null** [comment]
When I see how dynamically they develop it I think it will happen someday. Anyway, congrats on your open-source success ;)
I was able to get it working. Thanks again @GuardRex for help and good luck with your projects!

**Comment by guardrex** [comment]
I think that we figured out here that cwd wasn't supported and that's caused several devs a problem. I'm still working for Microsoft and slammed all the time these days. I won't be able to support cwd ... at least no time in the near future. Thanks tho for the suggestion/recommendation on how to improve the extension. Hopefully, VSC cats will come to their senses and give us a REAL task running toolbar in VSC.
