### ISSUE TITLE
Does not parse tasks.json containing comments

### ISSUE THREAD

**Issue by use-strict** [GuardRex/vscode-status-bar-tasks#2]
VSCode allows comments inside its *.json config files. This is invalid JSON and can't be parsed directly with JSON.parse, resulting in an error.

**Comment by guardrex** [comment]
@use-strict I noticed that too, which is why I pulled the comments out of the top of the sample JSON you see at the extension homepage in the Marketplace.

I'm using the JSON parser to read the file ...

``` c#
JSON.parse(fs.readFileSync(taskFilePath, 'utf8'));
```

Since the parser is following the JSON spec, where technically there shouldn't be comments in the file, it breaks if there are comments.

I agree with you in principle: Since VS Code allows comments, the extension should deal with them. I'm going to add some logic there to strip out comments (in memory where the file is read) before parsing with `JSON.parse()`. I'll get back to you soon when the update to the extension is posted.

**Comment by guardrex** [comment]
@use-strict First, I tried an npm module `strip-json-comments`; however, that worked in debug and broke in release. Therefore, I decided to do it the old fashioned way ... regex ...

``` typescript
var taskFileContents = 
  rawTaskFileContents.replace(/((\/\/|\/\/\/)(.+)(\r\n|\r|\n))|((\/\*)((\D|\d)+)(\*\/))/gi, "");
```

It's not very sophisticated, but that should remove the following types of comments ...

``` json
// This is a single line comment to remove
/// This is a single line comment to remove
/* This is a comment to remove */
/* This is a comment to remove
that spans multiple lines in a block.
*/
```

The updated version is online now in the VS Marketplace (v.0.0.5). I'll leave this open for a sec to hear back if it takes care of comments for you. Thanks for reporting (reminding) me about this problem.

**Comment by use-strict** [comment]
Very quick response, thanks. It almost works, except there are also empty lines with comments. Should be `(.*)` instead of `(.+)` and that should fix it I think.

e.g.:

```
// something
//
// something else
```

**Comment by guardrex** [comment]
@use-strict Yes! Indeed ... 0 or more matches ... not 1 or more. Update made (v.0.0.6). I'll leave open a bit longer to make sure we're good here. Thanks again for your help.

**Comment by guardrex** [comment]
@use-strict I think we have this one licked. I'll close now. Please re-open if this approach craps out. Thank you again for your help on this.
