### ISSUE TITLE
windows commands with spaces doesn't work

### ISSUE THREAD

**Issue by immeraufdemhund** [GuardRex/vscode-status-bar-tasks#21]
"tasks": [
        {
            "taskName": "build",
            "command": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\15.0\\Bin\\MSBuild.exe",
            "args": [
                "/clp:Summary",
                "/v:quiet"
            ],
            "problemMatcher": "$msCompile",
            "showOutput": "always",
            "echoCommand": true,
            "isBuildCommand": true
        }

with a simple tasks above I can hit ctrl+shift+b (or run task build from command pallete) and the command will work. I click on the build button from the status bar tasks and I get

`'C:\Program' is not recognized as an internal or external command, operable program or batch file.`

easy workaround that keeps all 3 working for me is to wrap it in double quotes, but this is to note the difference.

**Comment by guardrex** [comment]
Yes, I think your workaround will have to suffice. I've never needed spaces in the command. AFAIK you wouldn't be able to paste that in at a command prompt either and expect it to work without quotes. I wonder if the VSC folks to set it up with quotes internally for shell execution ... idk what they do to make it :sparkles: Just Work :sparkles:. I'm always using commands that are on the PATH. If your MSBuild was on the PATH, then I guess it would work fine as just `"command": "MSBuild.exe"`. I'm going to close because I think it's a shell characteristic or issue of not using a PATH entry. I'm a little scared of quoting the command internally without more info on whether or not VSC does it that way. Thanks tho for letting me know about this.
