### ISSUE TITLE
Permission denied error

### ISSUE THREAD

**Issue by use-strict** [GuardRex/vscode-status-bar-tasks#3]
Not sure if this is a problem with vscode or the extension. I'm getting this:

```
/bin/sh: 1: <path_to_build_js>: Permission denied
```

I have a task that looks like this:

```
"command": "nodejs",
"isShellCommand": true // doesn't seem to have any effect changing this
"tasks": [
    {
            "taskName": "build",
            "suppressTaskName": true,
            "showOutput": "silent",
            "isBuildCommand": true,
            "isWatching": true,
            "args": [ "<path_to_build_js>" ]
    }
]
```

Also, the output is going to "Project Task" channel. Is there a reason why it doesn't go to "Tasks" channel instead?

**Comment by guardrex** [comment]
@use-strict Does the task run normally if you run it manually (F1 -> T -> Tasks: Run Task -> build)? If that breaks, I guess its a VS Code/OS permissions issue. Even if that works but the status bar button doesn't work, I'd be at a bit of a loss on this. I did a quick search on elevating permissions from the command line, and there are some possibilities (but they're kind'a nasty):

http://stackoverflow.com/questions/19098101/how-to-open-an-elevated-cmd-using-command-line-for-windows

> the output is going to "Project Task" channel

Excellent! You triggered the answer to this. When I originally looked at the methods for Output Channel, I didn't see a way to get hold of the current `Tasks` panel ...

![capture3](https://cloud.githubusercontent.com/assets/1622880/13432051/decea01a-df80-11e5-8074-45b63e104b57.PNG)

... b/c I took the word "add" in `addOutputChannel` a bit too literally (and perhaps b/c I didn't read the API doc carefully enough). It turns out that you can name an existing panel. Therefore, I just needed to "add" the `Tasks` panel by name. I'll get this done after I hear back from you about the issue above with the permissions, but yes, we got this one. I'm glad you said something.

**Comment by use-strict** [comment]
The task runs OK with CTRL+SHIFT+B or "run task". I'm guessing the API exposed to the extension doesn't do the same thing as the main one. There must be something different. I see no other reason why one works and the other doesn't.

**Comment by guardrex** [comment]
Are you on Win OS?

**Comment by use-strict** [comment]
Ubuntu 14.

**Comment by guardrex** [comment]
Ah ... You got me on that one. Apparently, there is something diff between the two execution approaches. I can't think of anything from my research on tasks, and I know nothing at all about that OS.

**Comment by use-strict** [comment]
I will test this on Windows on my home computer and will try to do a little research as well.

**Comment by guardrex** [comment]
Ok. I'll leave this open for now in case something turns up.

I'll get the Tasks panel update done within a few hours. The new version will be 0.0.7.

**Comment by use-strict** [comment]
I see that you called `exec` directly. That probably leads to a permission error because of the execution context. Would something like this work instead?

```
vscode.commands.executeCommand("workbench.action.tasks.runTask", val.taskName);
```

I took the command from Preferences -> Keybinds (there is a list of available commands in the lower part)

**Comment by guardrex** [comment]
@use-strict I'm going to try that now and see what happens. Clearly, I went down the road of the npm child_process module. Maybe that was the wrong way to go. I'll see if I have some success with it. It would also totally solve the "Tasks" panel output issue, since it would be executing them as OOB VS Code tasks. I'll get back to you.

**Comment by guardrex** [comment]
Ah, yes. Now I recall why I had to go to the `child_process` module. I did try what you suggested very early when I first started writing the code. The result is that it opens the command palette and does **not** actually run the command ...

![capture](https://cloud.githubusercontent.com/assets/1622880/13435606/f35dcb1e-df8f-11e5-954a-17d8ff0c69c2.PNG)

**Comment by use-strict** [comment]
grrrr.....so I guess that's something that has to be implemented in the IDE. Unless there is some other way that we aren't aware of.

**Comment by guardrex** [comment]
that's right. I don't know of a way from my research on it how to directly trigger a task from the VS Code API. My workaround was to use npm `child_process`, which would work cross-plat (barring this permissions issue of course) to basically run the command directly.

Is there anyway you can run the entire VS Code application with elevated permissions?

**Comment by guardrex** [comment]
This is an issue that I can't address due to the limitation of the VS Code API. There is no direct way AFAICT to trigger tasks via the API. That's too bad, too, because it would have solved several other problems (e.g., the recent request to have variable substitution https://github.com/GuardRex/vscode-status-bar-tasks/issues/6). Since I can't fix this one, I'll close now.
