### ISSUE TITLE
I want to start in Terminal panel instead Output panel

### ISSUE THREAD

**Issue by lukaszpolowczyk** [GuardRex/vscode-status-bar-tasks#35]
@Example, start create-react-app:
{
			"label": "npm start",
			"type": "shell",
			"command": "npm start",
			"problemMatcher": [],
			"isBackground": true
		}
Click on status bar "npm start", show Output panel.
When click Tasks menu > Run Task > npm start, show Terminal panel, and Ii might stop server.
In addition, the "Show running tasks" icon will appear in the status bar with the number of taks running.

Opening in the terminal, and an icon of running tasks in the status bar. I need these two things.
Can you do it?

EDIT:
I found an extension that starts the task at vscode startup:
https://github.com/philfontaine/autolaunch

It turns on the task in the Terminal panel - as I wanted!
So it's possible!
Could you convert your extension so that the task opens with the terminal panel?
It has the two advantages I mentioned earlier.

**Comment by guardrex** [comment]
Thanks for the suggestion, but I'd prefer to have the extension just shell out the command to Node's `child_process` module. That's the only thing that I was going for with the extension. Of course, you're welcome to fork the repo and make a version that does what you need.

**Comment by guardrex** [comment]
Thanks for the suggestion, but I would like to just have the extension shell out the task. Of course, you can fork the repo and make a version of the extension that meets your needs.

**Comment by lukaszpolowczyk** [comment]
And could you add an option to be able to choose? I think there is nothing to do "competitive" extensions that differ so little.

**Comment by guardrex** [comment]
You can add it ... just fork the repo and you can change the code to do anything you like. I'm crazy busy with full-time work these days, and I just won't have time to expand the feature set of the extension. I'm really hoping that the VSC engineers add a toolbar that can run tasks to VSC. Then, I would be able to depreciate this extension. https://github.com/Microsoft/vscode/issues/41309

**Comment by bjg2** [comment]
Hey, this is real issue:
1) output pane is not interactive as terminal you can't stop the execution, add keyboard input, etc
2) output coloring is not working

understanding you have too much stuff to do (and already thankful for this extension you created) I forked and added showInTerminal option to tasks (if true output is in terminal, if anything else current behavior is preserved): https://github.com/bjg2/vscode-status-bar-tasks/commit/bcc798d4508166979d71a753910efd9380ea8d20.

Can you please merge this change into your codebase and update the vscode extension, so everyone else can use it (like the rest of my team)? Because this is great extension, thank you for that, with a minor but important missing feature...
