### ISSUE TITLE
Terminate Running Tasks

### ISSUE THREAD

**Issue by DBS06** [GuardRex/vscode-status-bar-tasks#37]
A nice feature would be to stop/kill/terminate running tasks.
VSCode would be possible to do that, but tasks which have been started over the status bar are not recognized as a task.

**Comment by guardrex** [comment]
That's correct. This extension uses Node's `child_process` module to shell out tasks. It's just the way that I built it, and it was built before VSC offered more control over tasks via their API.

I still hope that that the VSC people *wake up* and figure out that VSC needs a toolbar with the ability to run tasks as clickable buttons. A gazillion people ask for it, and they keep closing the issues as "out-of-scope."

Anyway, I'm not going to add this to this extension. I'm going to wait and hope the VSC engineers build a toolbar into VSC that can run tasks so that I can retire this extension.

https://github.com/Microsoft/vscode/issues/41309

**Comment by guardrex** [comment]
DAH! GH is flaking out this morning and double-posting my comments ... so I deleted one of them and it deleted the entire comment.

Anyway ... Thanks for the suggestion, but I would like to just have the extension shell out the task. Works for me, since I don't want them tied to VSC. This way, VSC can be closed, and the task will continue to run independently. This also goes back to the history of the extension. This extension was originally developed back when VSC didn't even offer task features in the API. Of course, you can fork the repo and make a version that meets your needs.

**Comment by DBS06** [comment]
Thanks for your answer, I will look into it and learn a little bit typescript :-)
