### ISSUE TITLE
Error when using tasks variable substitution

### ISSUE THREAD

**Issue by ntswor** [GuardRex/vscode-status-bar-tasks#6]
I'm currently trying to start following task:

```
"tasks": [
    {
      "taskName": "stylefmt",
      "suppressTaskName": true,
      "args": [
        "node tasks/node-stylefmt.js ${file} .... "
      ]
    }
  ]
```

But as it seems the variable substitution is not correctly filled:

```
formatting file: ${file}
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                                                  ^

Error: ENOENT: no such file or directory, open 'PATH\${file}'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (PATH\tasks\node-stylefmt.js:11:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```

Running the task directly is working though.

**Comment by guardrex** [comment]
@ntswor That's correct: The extension doesn't attempt to perform variable substitution. The contents of the `"args"` will are passed directly to Node's `child_process` module for execution. Whatever is in the string(s) becomes the command when the status bar task is clicked. This is a limitation of the extension just due to my available time.

The list of variable substitutions normally includes:
- ${workspaceRoot} the path of the folder opened in VS Code
- ${file} the current opened file
- ${fileBasename} the current opened file's basename
- ${fileDirname} the current opened file's dirname
- ${fileExtname} the current opened file's extension
- ${cwd} the task runner's current working directory on startup
- ${env.Name} for an environment variable ("Name" matches the env var name)

I think it's a great idea to have this feature rolled into the extension. Even I have a command that I would like to issue with the workspace root in it. Everytime I create a project and setup a `tasks.json` file, I have to manually change the path in the new file for the new project to match that project's path.

I'll see if I have time later today to work on this. I'll ping you back here with a progress report.

**Comment by guardrex** [comment]
@ntswor Didn't get to it today, but I think I'll have time on Thursday evening. I would like to get this one in there, so I hope to have good news to report on it shortly.

**Comment by ntswor** [comment]
@GuardRex thx, would appreciate it. You did a great work with the extension and I would like to use it for this too.

**Comment by guardrex** [comment]
@ntswor Thanks. I **almost** got done today with updates to a document that I've been working on for the past two days. I have to get the PR in on that first, then I can come over and work on this. I don't think it will take all that long. This is a simple string replacement with values that I should be able to grab easily from the VS Code API. I should get to this very soon ... Friday ... Saturday ... very soon.

**Comment by guardrex** [comment]
@ntswor Ok, I think we're on to something here. I just updated to v0.0.8, which has the new code in it for the variable replacements. I was able to do ...
- ${workspaceRoot} the path of the folder opened in VS Code
- ${file} the current opened file
- ${fileBasename} the current opened file's basename
- ${fileDirname} the current opened file's directory
- ${fileExtname} the current opened file's extension
- ${env.<ENVIRONMENT_VARIABLE_NAME>} environment variable (e.g., ${env.MY_ENV_VAR} will be replaced by the value of MY_ENV_VAR on the system or an empty string if the environment variable is not set).

I was unable to get to `${cwd}`, which is apparently the working directory where the task command is executed. I'm not going to do that one.

You can run a test for me on it, if you don't mind. Just use a task like this one ...

``` json
{
    "taskName": "status-bar-tasks test",
    "suppressTaskName": true,
    "args" : [ "echo", "Workspace: ${workspaceRoot} Full File Path: ${file} File Directory Path: ${fileDirname} File Basename: ${fileBasename} File Extension: ${fileExtname} OS Environment Variable Value: ${env.OS} Env Var Value Doesn't Exist: ${env.DOESNT_EXIST}"],
    "showOutput": "always",
    "isBuildCommand": false
}
```

... and it should output all of the var replacements for the currently open file. If no file is open, it will only replace the workspace path and the OS environment variable.

**Comment by ntswor** [comment]
Sorry for the late response - couldn't comment for some reason. 
Thanks for the changes. Works like a charm.

**Comment by guardrex** [comment]
np ... thx for the suggestion.
